[package]
name = "mls-srtp-client"
version = "0.1.0"
edition = "2024"
description = "MLS-SRTP demo client: creator, sender, or receiver"

[dependencies]
mls-srtp-core = { path = "../.." }
openmls = { workspace = true }
openmls_traits = { workspace = true }
srtp = { workspace = true }
hex = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
# for the ds_client module
ds-lib = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
base64 = { workspace = true }
# for the multicast module
socket2 = { workspace = true }
