[package]
name = "client-bob"
version = "0.1.0"
edition = "2021"
description = "Bob: MLS group joiner and SRTP multicast receiver"

[dependencies]
mls-srtp-common = { path = "../mls-srtp-common" }
openmls = { workspace = true }
openmls_traits = { workspace = true }
srtp = { workspace = true }
hex = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
